apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fju2drjxh-python
  janus-idp.io/tekton: fju2drjxh-python
  backstage.io/kubernetes-id: fju2drjxh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fju2drjxh-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
